export AZURE_KEYVAULT_NAME='azcourse-keyvault'
export AZURE_SQL_DBA_LOGIN='azcourse-admin'
export AZURE_SQL_DBA_PASS=''
export AZURE_SQL_APP_LOGIN='dblogin'
export AZURE_SQL_APP_PASS=''
export AZURE_FUNC_CODE=''